package com.usta.serviexpress.payments.dto;

import lombok.Data;

import java.util.Map;

/**
 * WompiWebhookDto
 *
 * Purpose:
 * - Data Transfer Object (DTO) representing the payload sent by Wompi webhooks.
 * - Used to capture transaction updates or other event notifications from Wompi in a structured form.
 *
 * Fields:
 * - event: The type of event received (e.g., "transaction.updated").
 * - data: A map containing the event payload. Typically includes a "transaction" object with keys:
 *         id, status, reference, amount_in_cents, and others depending on the event type.
 * - timestamp: The ISO8601 timestamp when the event was generated by Wompi.
 * - signature: Optional HMAC-SHA256 signature of the payload. Should be validated against your integrity secret
 *              if security verification is needed.
 *
 * Notes:
 * - The 'data' field is a generic Map<String,Object> to accommodate varying webhook structures.
 * - When processing, safely cast nested objects and handle missing fields to avoid runtime errors.
 * - Signature validation is recommended for security; failing to validate can lead to accepting fraudulent events.
 */
@Data
public class WompiWebhookDto {

    /** Event type identifier sent by Wompi, e.g., "transaction.updated". */
    private String event;

    /** Event payload; typically contains a nested "transaction" object. */
    private Map<String,Object> data;

    /** ISO8601 timestamp string when the event occurred. */
    private String timestamp;

    /** Optional integrity signature for webhook validation. */
    private String signature;
}

/*
Summary (Technical Note):
WompiWebhookDto serves as a structured representation of webhook notifications from Wompi.
It captures the event type, payload data, timestamp, and optional signature.
The DTO is intended for use in webhook controllers/services that need to handle payment
events, validate integrity, and extract transaction details for further processing.
*/
