package com.usta.serviexpress.Entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Data;

import java.io.Serializable;

/**
 * UsuarioEntity
 *
 * Purpose:
 * - Represents a user in the system, which could be a client or a service provider.
 * - Stores basic user information such as email, password, username, contact, location, and role.
 * - Ensures uniqueness of email via database constraints.
 *
 * Persistence mapping:
 * - Mapped to the "usuarios" table.
 * - Uses unique constraint on the "correo" column to avoid duplicate emails.
 *
 * Notes:
 * - Roles are linked via a many-to-one relationship.
 * - Additional optional fields like phone number and city are included.
 * - Placeholder setters for availability and rate are present but do not persist data; may be implemented later.
 */
@Data
@Entity
@Table(
        name = "usuarios",
        uniqueConstraints = @UniqueConstraint(name = "uk_usuarios_correo", columnNames = "correo")
)
@JsonIgnoreProperties({"hibernateLazyInitializer","handler"})
public class UsuarioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    /** Default no-argument constructor required by JPA */
    public UsuarioEntity() { }

    /**
     * Convenience constructor to create a new user instance with email, password, and username
     * @param correo - user's email, must be unique
     * @param clave - user's password
     * @param nombreUsuario - display username
     */
    public UsuarioEntity(String correo, String clave, String nombreUsuario) {
        this.correo = correo;
        this.clave = clave;
        this.nombreUsuario = nombreUsuario;
    }

    /** Primary key for the user entity, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_usuario")
    private Long idUsuario;

    /** User's email address, must be unique */
    @Column(name = "correo", nullable = false, length = 120)
    private String correo;

    /** User's password (stored as plain text or hashed externally) */
    @Column(name = "clave", nullable = false, length = 120)
    private String clave;

    /** Username or display name for the user */
    @Column(name = "nombre_usuario", nullable = false, length = 80)
    private String nombreUsuario;

    /** Optional contact phone number */
    @Column(name = "telefono", length = 30)
    private String telefono;

    /** Optional city/location of the user */
    @Column(name = "ciudad", length = 80)
    private String ciudad;

    /**
     * Role of the user (client, provider, admin, etc.)
     * - Many users can share the same role.
     * - Fetch type LAZY to avoid unnecessary loading of role data.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_rol", nullable = false)
    private RolEntity rol;

    /**
     * Placeholder setter for provider availability.
     * - Currently does nothing; could be implemented in the future.
     * @param disponibilidad - desired availability state
     */
    public void setDisponibilidad(boolean disponibilidad) { }

    /**
     * Placeholder setter for provider rate.
     * - Currently does nothing; could be implemented in the future.
     * @param tarifa - desired rate value
     */
    public void setTarifa(double tarifa) { }
}

/**
 * Summary:
 * This entity models system users, storing essential information including email, password, 
 * username, contact details, city, and role. The email is constrained to be unique. 
 * It supports relationships to roles and provides placeholders for future provider-specific fields 
 * like availability and rate.
 */
